// crates/biome_html_parser/benches/fixtures/synthetic/svelte-expressions.svelte
<script>
  let firstName = 'John';
  let lastName = 'Doe';
  let age = 30;
  let items = [1, 2, 3, 4, 5];
  let user = { profile: { name: 'Alice', settings: { theme: 'dark' } } };
  let htmlContent = '<strong>Bold text</strong>';
  let condition = true;
  let count = 0;
  let price = 19.99;
  let currency = 'USD';
  let formattedDate = new Date().toLocaleDateString();
  let items2 = [{ name: 'A', value: 1 }, { name: 'B', value: 2 }];
</script>

<div class="expressions-container">
  <h1>Welcome, {firstName} {lastName}!</h1>
  <p>Age: {age} years old</p>
  <p>Full name length: {(firstName + ' ' + lastName).length}</p>
  <p>Uppercase: {firstName.toUpperCase()} {lastName.toUpperCase()}</p>
  <p>Is adult: {age >= 18 ? 'Yes' : 'No'}</p>
  <p>Next year: {age + 1}</p>
  <p>Decades lived: {Math.floor(age / 10)}</p>
  
  <div>
    <span>Count: {count}</span>
    <span>Double: {count * 2}</span>
    <span>Triple: {count * 3}</span>
    <span>Square: {count ** 2}</span>
    <span>Is even: {count % 2 === 0}</span>
  </div>

  <p>Price: {price.toFixed(2)} {currency}</p>
  <p>Discounted: {(price * 0.9).toFixed(2)}</p>
  <p>Tax included: {(price * 1.2).toFixed(2)}</p>
  <p>Formatted: {new Intl.NumberFormat('en-US', { style: 'currency', currency }).format(price)}</p>

  <p>Date: {formattedDate}</p>
  <p>Timestamp: {Date.now()}</p>
  <p>Random: {Math.random().toFixed(4)}</p>
  <p>PI: {Math.PI.toFixed(5)}</p>

  <ul>
    {#each items as item, i}
      <li>
        Index: {i}, Value: {item}, 
        Square: {item ** 2}, 
        Cube: {item ** 3},
        Is even: {item % 2 === 0 ? 'yes' : 'no'},
        Double: {item * 2}
      </li>
    {/each}
  </ul>

  <p>Nested: {user.profile.name} - Theme: {user.profile.settings.theme}</p>
  <p>Computed: {items.reduce((a, b) => a + b, 0)}</p>
  <p>Average: {(items.reduce((a, b) => a + b, 0) / items.length).toFixed(2)}</p>
  <p>Max: {Math.max(...items)}</p>
  <p>Min: {Math.min(...items)}</p>

  {@html htmlContent}
  {@html '<div class="injected">' + htmlContent + '</div>'}
  {@html condition ? '<span>True</span>' : '<span>False</span>'}
  {@html items.map(i => `<span>${i}</span>`).join('')}

  {@const fullName = firstName + ' ' + lastName}
  {@const initials = firstName[0] + lastName[0]}
  {@const reversed = firstName.split('').reverse().join('')}
  {@const doubled = items.map(x => x * 2)}
  {@const filtered = items.filter(x => x > 2)}
  {@const sum = items.reduce((a, b) => a + b, 0)}
  {@const avg = sum / items.length}
  {@const greeting = `Hello, ${fullName}!`}
  {@const isValid = firstName.length > 0 && lastName.length > 0}
  {@const displayName = fullName || 'Anonymous'}
  {@const status = age >= 18 ? 'adult' : 'minor'}
  {@const category = age < 13 ? 'child' : age < 20 ? 'teen' : 'adult'}

  <p>Full name: {fullName}</p>
  <p>Initials: {initials}</p>
  <p>Reversed: {reversed}</p>
  <p>Doubled: {doubled.join(', ')}</p>
  <p>Filtered: {filtered.join(', ')}</p>
  <p>Sum: {sum}</p>
  <p>Average: {avg.toFixed(2)}</p>
  <p>Greeting: {greeting}</p>
  <p>Valid: {isValid}</p>
  <p>Display: {displayName}</p>
  <p>Status: {status}</p>
  <p>Category: {category}</p>

  {@debug firstName, lastName, age, items}
  {@debug user, condition, count}
  {@debug items2}

  <p>Boolean: {true} {false}</p>
  <p>Null/Undefined: {null} {undefined}</p>
  <p>Array length: {items.length}</p>
  <p>String methods: {'hello'.toUpperCase()} {'WORLD'.toLowerCase()}</p>
  <p>Template: {`Count: ${count}`}</p>
  <p>Expression: {(2 + 3) * 4}</p>
  <p>Comparison: {5 > 3} {5 < 3} {5 === 5}</p>
  <p>Logical: {true && 'yes'} {false || 'no'}</p>
  <p>Nullish: {null ?? 'default'} {undefined ?? 'fallback'}</p>
  <p>Optional: {user?.profile?.name}</p>
</div>

// crates/biome_html_parser/benches/fixtures/walltime/vue-expressions.vue
<template>
  <div class="expression-heavy">
    <h1>{{ pageTitle || 'Default Title' }} - {{ pageSubtitle }}</h1>
    <p>Welcome {{ user ? user.name : 'Guest' }}! You have {{ notifications.length }} new {{ notifications.length === 1 ? 'notification' : 'notifications' }}.</p>
    
    <div class="stats">
      <span>Total: {{ items.reduce((sum, item) => sum + item.value, 0) }}</span>
      <span>Average: {{ items.length ? items.reduce((sum, item) => sum + item.value, 0) / items.length : 0 }}</span>
      <span>Max: {{ Math.max(...items.map(i => i.value)) }}</span>
      <span>Min: {{ Math.min(...items.map(i => i.value)) }}</span>
    </div>
    
    <ul>
      <li v-for="item in items" :key="item.id">
        {{ item.name }} - {{ item.description || 'No description' }} ({{ item.status === 'active' ? 'Active' : item.status === 'pending' ? 'Pending' : 'Inactive' }})
        <span v-if="item.tags && item.tags.length">Tags: {{ item.tags.join(', ') }}</span>
        <span v-else>No tags</span>
        Price: ${{ item.price ? item.price.toFixed(2) : '0.00' }}
        Discount: {{ item.discount ? (item.price * (1 - item.discount)).toFixed(2) : item.price ? item.price.toFixed(2) : '0.00' }}
      </li>
    </ul>
    
    <div class="computed">
      <p>Full Name: {{ user ? `${user.firstName} ${user.lastName}` : 'Anonymous' }}</p>
      <p>Formatted Date: {{ new Date(timestamp).toLocaleDateString() }}</p>
      <p>Uppercase: {{ message ? message.toUpperCase() : '' }}</p>
      <p>Reversed: {{ message ? message.split('').reverse().join('') : '' }}</p>
      <p>Filtered: {{ items.filter(i => i.active).map(i => i.name).join(', ') }}</p>
    </div>
    
    <form>
      <label>Name: {{ formData.name || 'Empty' }}</label>
      <label>Email: {{ formData.email ? formData.email.toLowerCase() : 'Not provided' }}</label>
      <label>Age: {{ formData.birthDate ? new Date().getFullYear() - new Date(formData.birthDate).getFullYear() : 'Unknown' }}</label>
      <label>Country: {{ formData.country || 'Not selected' }} ({{ formData.country ? getCountryCode(formData.country) : 'N/A' }})</label>
    </form>
    
    <table>
      <tr v-for="row in tableData" :key="row.id">
        <td>{{ row.index + 1 }}</td>
        <td>{{ row.name }}</td>
        <td>{{ row.values.reduce((a, b) => a + b, 0) }}</td>
        <td>{{ row.values.length ? (row.values.reduce((a, b) => a + b, 0) / row.values.length).toFixed(2) : '0.00' }}</td>
        <td>{{ row.enabled ? 'Yes' : 'No' }}</td>
        <td>{{ row.metadata ? JSON.stringify(row.metadata) : '{}' }}</td>
      </tr>
    </table>
    
    <div class="nested">
      <p>Level 1: {{ data.level1 ? data.level1.value : 'N/A' }}</p>
      <p>Level 2: {{ data.level1 && data.level1.level2 ? data.level1.level2.value : 'N/A' }}</p>
      <p>Level 3: {{ data.level1 && data.level1.level2 && data.level1.level2.level3 ? data.level1.level2.level3.value : 'N/A' }}</p>
      <p>Array access: {{ arr && arr[0] ? arr[0].name : 'None' }}</p>
      <p>Method call: {{ getValue() || 'Default' }}</p>
      <p>Computed prop: {{ computedValue }}</p>
    </div>
    
    <footer>
      <span>{{ footer.left }}</span>
      <span>{{ footer.center }}</span>
      <span>{{ footer.right }}</span>
      <span>Rendered at: {{ new Date().toISOString() }}</span>
    </footer>
  </div>
</template>

<script setup>
import { ref, computed } from 'vue'

const pageTitle = ref('Dashboard')
const pageSubtitle = ref('Overview')
const user = ref({ name: 'John', firstName: 'John', lastName: 'Doe' })
const notifications = ref([1, 2, 3])
const items = ref([
  { id: 1, name: 'Item 1', value: 10, status: 'active', tags: ['a', 'b'], price: 99.99, discount: 0.1, active: true },
  { id: 2, name: 'Item 2', value: 20, status: 'pending', tags: [], price: 49.99, active: false },
  { id: 3, name: 'Item 3', value: 30, status: 'inactive', price: 29.99, active: true }
])
const timestamp = ref(Date.now())
const message = ref('Hello World')
const formData = ref({ name: 'Test', email: 'TEST@EXAMPLE.COM', birthDate: '1990-01-01', country: 'USA' })
const tableData = ref([
  { id: 1, index: 0, name: 'Row 1', values: [1, 2, 3], enabled: true, metadata: { key: 'value' } },
  { id: 2, index: 1, name: 'Row 2', values: [4, 5, 6], enabled: false }
])
const data = ref({ level1: { value: 1, level2: { value: 2, level3: { value: 3 } } } })
const arr = ref([{ name: 'First' }])
const footer = ref({ left: 'Left', center: 'Center', right: 'Right' })

const getCountryCode = (country) => country.slice(0, 2).toUpperCase()
const getValue = () => 'computed'
const computedValue = computed(() => 'value')
</script>

<style scoped>
.expression-heavy { padding: 20px; }
.stats span { margin-right: 20px; }
</style>
